### ISSUE TITLE
Remove unused dependency and add a start script

### ISSUE THREAD

**Issue by scorpion9979** [PaulRBerg/typescript-template#1]
Remove `ts-node` dependency from `package.json` as it's not being used anywhere. Also, include a start script there as follows:

```
...,
scripts: {
  "start": "node .",
  ...
```

**Comment by paulrberg** [comment]
Indeed, `ts-node` is not used directly, but I included it as a nice-to-have. You can run TS directly with `ts-node`, without having to first build the TS code with `tsc build`.
